[package]
name = "looker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
atty = "0.2.14"
chrono = { version = "0.4.19", features = ["serde"] }
getopts = "0.2.21"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_repr = "0.1.8"
